### ISSUE TITLE
Change resolution state and change URIs

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv-Change#5]
Every `VitruviusChange` has a URI, at least if it is calculatable. If a change is resolved and applied it is easy to determine its URI during that process. If changes are recorded and transformed into `VitruviusChanges` it is sometimes not possible to identify the URI, e.g. because the modified element was just removed from its resource.

To make the change URIs more meaningful, I propose the following:
- All changes (also `EChanges`) get a URI, which is set on their creation.
- All changes (both `EChanges` and `VitruviusChanges`) manage their resolution state.
- Resolved changes always have a valid URI according to what they were applied to or recorded from
- Unresolved changes have not URI set (just like they have no affected object etc.)

**Comment by TomWerm** [comment]
Continued in #59
