### ISSUE TITLE
Undocumented `DeltaResource`

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv-Change#72]
#63 introduces `DeltaBasedResource` and `DeltaBasedResourceFactory` with no documentation at all. It appears they serve as some sort of serialization of changes I guess?
I don't see the reason for doing this by extending a `Resource` instead of - as in all other cases, e.g. `UuidResolver` - provide a regular store / load interface. Additionally, I don't see the semantic overlap with the `changederivation` package where it is placed.

**Comment by TomWerm** [comment]
DeltaBasedResource serves as delta based serialisation of resources. As the Resource type management in EMF uses registries, I am not sure why you would implement different interfaces for the same purpose beside the already existing ones? The idea is to hide the serialisation (and to build additional functionality on top of the deltas later). The semantic overlap is indeed not ideal, we may move both classes into their own (util) project.

**Comment by JanWittler** [comment]
Ah, now I get more the purpose. Then maybe one side comment on the general approach: Deriving changes directly from the resource might be tempting but it is not perfect and I had several experiences with UML and EMF Compare that the derived changes could not be applied anymore. As such, it might be worth considering to rather store the `List<PropagatedChange>` which is obtained from `VirtualModel::propagateChange`. This would also automatically allow for some commit-based (or other unit) versioning, as each list of propagated changes represents an entire consistency preservation roundtrip.

Anyways, if you decide to keep it like this, please add some documentation ;) (and tests are also missing)
